### PR TITLE
Fix closing the browser and effectively making Karma stuck when using singleRun option

### PR DESCRIPTION
**Pull request by dos1**
There were a few problems that prevented selenium-webdriver-launcher to work properly with singleRun option:
* the browser id wasn't passed to the browser in URL, so the browser generated a new ID, which Karma then treated as a unrelated, new browser
* lack of baseBrowserDecorator prevented some internal browser registration code from being called
* after adding baseBrowserDecorator, self.forceKill was defined erroneously (killingPromise was referring to the one in decorator's scope, which was never set due to self.kill being redefined in SeleniumWebdriverBrowser)

### CODE REVIEW

**Comment by PixnBits** [comment]
Good stuff, thanks for fixing that!

**Comment by erykpiast** [comment]
:+1:

**Comment by PixnBits** [comment]
oops, got busy at work :-1: I can give you access to do so, if you wish? might be faster than I'll be :(

**Comment by PixnBits** [comment]
I don't see @dos1 on npm :frowning:

**Comment by dos1** [comment]
Try again :)

**Comment by PixnBits** [comment]
published in the meantime

**Comment by PixnBits** [comment]
and added!

**Comment by dos1** [comment]
Great, thanks! :+1:

**Pull request merged**
